let dados = [
    {
        nome: "Universidade de Brasília (UnB)",
        descricao: "A Universidade de Brasília (UnB) é uma universidade pública federal brasileira, localizada em Brasília. Fundada em 1962, é conhecida pela sua excelência acadêmica, oferecendo uma ampla gama de cursos e promovendo pesquisa de ponta.",
        link: "https://www.unb.br",
        cidade: "Brasília",
    },
    {
        nome: "Universidade Federal da Grande Dourados (UFGD)",
        descricao: "A Universidade Federal da Grande Dourados (UFGD) é uma universidade pública federal brasileira, localizada em Dourados, Mato Grosso do Sul. Fundada em 2005, a UFGD se dedica ao ensino superior, pesquisa e extensão, com foco no desenvolvimento regional.",
        link: "https://www.ufgd.edu.br",
        cidade: "Dourados",
    },
    {
        nome: "Universidade Federal de Goiás (UFG)",
        descricao: "A Universidade Federal de Goiás (UFG) é uma universidade pública federal brasileira, situada em Goiânia, Goiás. Fundada em 1960, a UFG é reconhecida por sua qualidade acadêmica e pelo incentivo à pesquisa e inovação.",
        link: "https://www.ufg.br",
        cidade: "Goiânia",
    },
    {
        nome: "Universidade Federal de Mato Grosso (UFMT)",
        descricao: "A Universidade Federal de Mato Grosso (UFMT) é uma universidade pública federal brasileira, com sede em Cuiabá, Mato Grosso. Fundada em 1970, a UFMT oferece uma ampla gama de cursos e programas, além de se destacar em pesquisa e extensão.",
        link: "https://www.ufmt.br",
        cidade: "Cuiabá",
    },
    {
        nome: "Universidade Federal de Mato Grosso do Sul (UFMS)",
        descricao: "A Universidade Federal de Mato Grosso do Sul (UFMS) é uma universidade pública federal brasileira, localizada em Campo Grande, Mato Grosso do Sul. Fundada em 1979, a UFMS é conhecida por sua contribuição ao ensino superior e à pesquisa na região.",
        link: "https://www.ufms.br",
        cidade: "Campo Grande",
    },
    {
        nome: "Universidade Federal de Catalão (UFCat)",
        descricao: "A Universidade Federal de Catalão (UFCat) é uma universidade pública federal brasileira, localizada em Catalão, Goiás. Fundada em 2000, a UFCat foca em oferecer educação de qualidade e promover a pesquisa científica.",
        link: "https://www.ufcat.edu.br",
        cidade: "Catalão",
    },
    {
        nome: "Universidade Federal de Jataí (UFJ)",
        descricao: "A Universidade Federal de Jataí (UFJ) é uma universidade pública federal brasileira, situada em Jataí, Goiás. Fundada em 2001, a UFJ se dedica ao ensino e à pesquisa, contribuindo para o desenvolvimento local e regional.",
        link: "https://www.ufj.edu.br",
        cidade: "Jataí",
    },
    {
        nome: "Universidade Federal de Rondonópolis (UFR)",
        descricao: "A Universidade Federal de Rondonópolis (UFR) é uma universidade pública federal brasileira, localizada em Rondonópolis, Mato Grosso. Fundada em 2008, a UFR busca promover o ensino superior e a pesquisa na região.",
        link: "https://www.ufr.br",
        cidade: "Rondonópolis",
    },
    {
        nome: "Universidade Federal da Bahia (UFBA)",
        descricao: "A Universidade Federal da Bahia (UFBA) é uma das mais antigas e prestigiadas universidades do Brasil. Fundada em 1808, a UFBA oferece uma ampla gama de cursos de graduação e pós-graduação, além de desenvolver pesquisas de ponta em diversas áreas do conhecimento.",
        link: "https://www.ufba.br/",
        cidade: "Salvador",
    },
    {
        nome: "Universidade Federal do Sul da Bahia (UFSB)",
        descricao: "A Universidade Federal do Sul da Bahia (UFSB) é uma universidade pública federal brasileira, com sede em Porto Seguro, Bahia. Fundada em 2013, a UFSB tem como missão promover a educação superior e o desenvolvimento regional sustentável.",
        link: "https://www.ufsb.edu.br",
        cidade: "Porto Seguro",
    },
    {
        nome: "Universidade Federal da Lusofonia Afro-Brasileira (UFLAB)",
        descricao: "A Universidade Federal da Lusofonia Afro-Brasileira (UFLAB) é uma universidade pública federal brasileira, localizada em São Luís, Maranhão. Fundada em 2010, a UFLAB se dedica ao estudo da Lusofonia e à integração cultural.",
        link: "https://www.uflab.edu.br",
        cidade: "São Luís",
    },
    {
        nome: "Universidade Federal da Paraíba (UFPB)",
        descricao: "A Universidade Federal da Paraíba (UFPB) é uma universidade pública federal brasileira, situada em João Pessoa, Paraíba. Fundada em 1955, a UFPB oferece uma variedade de cursos e se destaca em pesquisa e extensão.",
        link: "https://www.ufpb.br",
        cidade: "João Pessoa",
    },
    {
        nome: "Universidade Federal do Cariri (UFCA)",
        descricao: "A Universidade Federal do Cariri (UFCA) é uma universidade pública federal brasileira, localizada em Crato, Ceará. Fundada em 2005, a UFCA é focada no desenvolvimento regional e na oferta de educação de qualidade.",
        link: "https://www.ufca.edu.br",
        cidade: "Crato",
    },
    {
        nome: "Universidade Federal de Alagoas (UFAL)",
        descricao: "A Universidade Federal de Alagoas (UFAL) é uma universidade pública federal brasileira, com sede em Maceió, Alagoas. Fundada em 1961, a UFAL é reconhecida pela qualidade de seu ensino e pesquisa.",
        link: "https://www.ufal.br",
        cidade: "Maceió",
    },
    {
        nome: "Universidade Federal de Campina Grande (UFCG)",
        descricao: "A Universidade Federal de Campina Grande (UFCG) é uma universidade pública federal brasileira, localizada em Campina Grande, Paraíba. Fundada em 2002, a UFCG é destacada por sua pesquisa e inovação tecnológica.",
        link: "https://www.ufcg.edu.br",
        cidade: "Campina Grande",
    },
    {
        nome: "Universidade Federal de Pernambuco (UFPE)",
        descricao: "A Universidade Federal de Pernambuco (UFPE) é uma universidade pública federal brasileira, situada em Recife, Pernambuco. Fundada em 1946, a UFPE é conhecida por seu compromisso com a excelência acadêmica e a pesquisa.",
        link: "https://www.ufpe.br",
        cidade: "Recife",
    },
    {
        nome: "Universidade Federal de Sergipe (UFS)",
        descricao: "A Universidade Federal de Sergipe (UFS) é uma universidade pública federal brasileira, localizada em São Cristóvão, Sergipe. Fundada em 1967, a UFS oferece uma ampla gama de cursos e programas acadêmicos.",
        link: "https://www.ufs.br",
        cidade: "São Cristóvão",
    },
    {
        nome: "Universidade Federal do Ceará (UFC)",
        descricao: "A Universidade Federal do Ceará (UFC) é uma universidade pública federal brasileira, situada em Fortaleza, Ceará. Fundada em 1954, a UFC é renomada por sua qualidade no ensino e pesquisa.",
        link: "https://www.ufc.br",
        cidade: "Fortaleza",
    },
    {
        nome: "Universidade Federal do Maranhão (UFMA)",
        descricao: "A Universidade Federal do Maranhão (UFMA) é uma universidade pública federal brasileira, localizada em São Luís, Maranhão. Fundada em 1966, a UFMA se destaca pela sua contribuição para o desenvolvimento acadêmico e científico.",
        link: "https://www.ufma.br",
        cidade: "São Luís",
    },
    {
        nome: "Universidade Federal do Oeste da Bahia (UFOB)",
        descricao: "A Universidade Federal do Oeste da Bahia (UFOB) é uma universidade pública federal brasileira, com sede em Barreiras, Bahia. Fundada em 2010, a UFOB visa promover a educação superior e a pesquisa na região oeste da Bahia.",
        link: "https://www.ufob.edu.br",
        cidade: "Barreiras",
    },
    {
        nome: "Universidade Federal do Piauí (UFPI)",
        descricao: "A Universidade Federal do Piauí (UFPI) é uma universidade pública federal brasileira, situada em Teresina, Piauí. Fundada em 1971, a UFPI oferece uma ampla gama de cursos e se destaca na pesquisa e extensão.",
        link: "https://www.ufpi.br",
        cidade: "Teresina",
    },
    {
        nome: "Universidade Federal do Rio Grande do Norte (UFRN)",
        descricao: "A Universidade Federal do Rio Grande do Norte (UFRN) é uma universidade pública federal brasileira, localizada em Natal, Rio Grande do Norte. Fundada em 1960, a UFRN é conhecida por seu ensino de excelência e atividades de pesquisa.",
        link: "https://www.ufrn.br",
        cidade: "Natal",
    },
    {
        nome: "Universidade Federal do Vale do São Francisco (UNIVASF)",
        descricao: "A Universidade Federal do Vale do São Francisco (UNIVASF) é uma universidade pública federal brasileira, com campus em Petrolina e outras cidades do Vale do São Francisco. Fundada em 2002, a UNIVASF se destaca por suas contribuições ao ensino e à pesquisa na região.",
        link: "https://www.univasf.edu.br",
        cidade: "Petrolina",
    },
    {
        nome: "Universidade Federal Rural de Pernambuco (UFRPE)",
        descricao: "A Universidade Federal Rural de Pernambuco (UFRPE) é uma universidade pública federal brasileira, situada em Recife, Pernambuco. Fundada em 1912, a UFRPE é especializada em áreas rurais e agrárias, além de outras disciplinas.",
        link: "https://www.ufrpe.br",
        cidade: "Recife",
    },
    {
        nome: "Universidade Federal Rural do Semi-Árido (UFERSA)",
        descricao: "A Universidade Federal Rural do Semi-Árido (UFERSA) é uma universidade pública federal brasileira, localizada em Mossoró, Rio Grande do Norte. Fundada em 2005, a UFERSA é conhecida por seu foco no desenvolvimento rural e regional.",
        link: "https://www.ufersa.edu.br",
        cidade: "Mossoró",
    },
    {
        nome: "Universidade Federal de Rondônia (UNIR)",
        descricao: "A Universidade Federal de Rondônia (UNIR) é uma universidade pública federal brasileira, com sede em Porto Velho, Rondônia. Fundada em 1989, a UNIR oferece uma ampla gama de cursos e contribui para a pesquisa e o desenvolvimento regional.",
        link: "https://www.unir.br",
        cidade: "Porto Velho",
    },
    {
        nome: "Universidade Federal de Roraima (UFRR)",
        descricao: "A Universidade Federal de Roraima (UFRR) é uma universidade pública federal brasileira, situada em Boa Vista, Roraima. Fundada em 1989, a UFRR tem como objetivo promover a educação superior e a pesquisa na região amazônica.",
        link: "https://www.ufrr.br",
        cidade: "Boa Vista",
    },
    {
        nome: "Universidade Federal do Acre (UFAC)",
        descricao: "A Universidade Federal do Acre (UFAC) é uma universidade pública federal brasileira, localizada em Rio Branco, Acre. Fundada em 1962, a UFAC é conhecida pela sua contribuição ao ensino superior e à pesquisa na região amazônica.",
        link: "https://www.ufac.br",
        cidade: "Rio Branco",
    },
    {
        nome: "Universidade Federal do Amapá (UNIFAP)",
        descricao: "A Universidade Federal do Amapá (UNIFAP) é uma universidade pública federal brasileira, com sede em Macapá, Amapá. Fundada em 1990, a UNIFAP oferece cursos em diversas áreas do conhecimento e promove pesquisa científica.",
        link: "https://www.unifap.br",
        cidade: "Macapá",
    },
    {
        nome: "Universidade Federal do Amazonas (UFAM)",
        descricao: "A Universidade Federal do Amazonas (UFAM) é uma universidade pública federal brasileira, localizada em Manaus, Amazonas. Fundada em 1909, a UFAM é renomada por sua pesquisa na região amazônica e sua excelência acadêmica.",
        link: "https://www.ufam.edu.br",
        cidade: "Manaus",
    },
    {
        nome: "Universidade Federal do Oeste do Pará (UFOPA)",
        descricao: "A Universidade Federal do Oeste do Pará (UFOPA) é uma universidade pública federal brasileira, situada em Santarém, Pará. Fundada em 2008, a UFOPA se dedica ao ensino superior e à pesquisa na região do Oeste do Pará.",
        link: "https://www.ufopa.edu.br",
        cidade: "Santarém",
    },
    {
        nome: "Universidade Federal do Pará (UFPA)",
        descricao: "A Universidade Federal do Pará (UFPA) é uma universidade pública federal brasileira, com sede em Belém, Pará. Fundada em 1957, a UFPA é destacada por suas atividades de ensino, pesquisa e extensão na região amazônica.",
        link: "https://www.ufpa.br",
        cidade: "Belém",
    },
    {
        nome: "Universidade Federal do Tocantins (UFT)",
        descricao: "A Universidade Federal do Tocantins (UFT) é uma universidade pública federal brasileira, localizada em Palmas, Tocantins. Fundada em 2000, a UFT oferece uma ampla gama de cursos e programas, além de promover a pesquisa e a inovação.",
        link: "https://www.uft.edu.br",
        cidade: "Palmas",
    },
    {
        nome: "Universidade Federal Rural da Amazônia (UFRA)",
        descricao: "A Universidade Federal Rural da Amazônia (UFRA) é uma universidade pública federal brasileira, com sede em Belém, Pará. Fundada em 2005, a UFRA foca no desenvolvimento rural e na pesquisa científica na região amazônica.",
        link: "https://www.ufra.edu.br",
        cidade: "Belém",
    },
    {
        nome: "Universidade Federal do Sul e Sudeste do Pará (UNIFESSPA)",
        descricao: "A Universidade Federal do Sul e Sudeste do Pará (UNIFESSPA) é uma universidade pública federal brasileira, localizada em Marabá, Pará. Fundada em 2013, a UNIFESSPA é dedicada ao ensino superior e à pesquisa na região sul e sudeste do Pará.",
        link: "https://www.unifesspa.edu.br",
        cidade: "Marabá",
    },
    {
        nome: "Universidade Federal de Alfenas (UNIFAL)",
        descricao: "A Universidade Federal de Alfenas (UNIFAL) é uma universidade pública federal brasileira, localizada em Alfenas, Minas Gerais. Fundada em 2004, a UNIFAL é conhecida por sua excelência acadêmica e programas de pesquisa.",
        link: "https://www.unifal-mg.edu.br",
        cidade: "Alfenas",
    },
    {
        nome: "Universidade Federal de Itajubá (UNIFEI)",
        descricao: "A Universidade Federal de Itajubá (UNIFEI) é uma universidade pública federal brasileira, situada em Itajubá, Minas Gerais. Fundada em 1913, a UNIFEI é renomada por seus cursos de engenharia e ciência e tecnologia.",
        link: "https://www.unifei.edu.br",
        cidade: "Itajubá",
    },
    {
        nome: "Universidade Federal de Juiz de Fora (UFJF)",
        descricao: "A Universidade Federal de Juiz de Fora (UFJF) é uma universidade pública federal brasileira, localizada em Juiz de Fora, Minas Gerais. Fundada em 1960, a UFJF é conhecida por sua excelência acadêmica e de pesquisa.",
        link: "https://www.ufjf.br",
        cidade: "Juiz de Fora",
    },
    {
        nome: "Universidade Federal de Lavras (UFLA)",
        descricao: "A Universidade Federal de Lavras (UFLA) é uma universidade pública federal brasileira, situada em Lavras, Minas Gerais. Fundada em 1908, a UFLA é destacada por suas atividades acadêmicas e de pesquisa, especialmente nas áreas de ciências agrárias.",
        link: "https://www.ufla.br",
        cidade: "Lavras",
    },
    {
        nome: "Universidade Federal de Minas Gerais (UFMG)",
        descricao: "A Universidade Federal de Minas Gerais (UFMG) é uma universidade pública federal brasileira, localizada em Belo Horizonte, Minas Gerais. Fundada em 1927, a UFMG é uma das mais renomadas instituições de ensino superior do Brasil, com forte presença em pesquisa e inovação.",
        link: "https://www.ufmg.br",
        cidade: "Belo Horizonte",
    },
    {
        nome: "Universidade Federal de Ouro Preto (UFOP)",
        descricao: "A Universidade Federal de Ouro Preto (UFOP) é uma universidade pública federal brasileira, com sede em Ouro Preto, Minas Gerais. Fundada em 1969, a UFOP é conhecida por sua tradição acadêmica e pesquisa, especialmente nas áreas de ciências humanas e exatas.",
        link: "https://www.ufop.br",
        cidade: "Ouro Preto",
    },
    {
        nome: "Universidade Federal de São Carlos (UFSCar)",
        descricao: "A Universidade Federal de São Carlos (UFSCar) é uma universidade pública federal brasileira, situada em São Carlos, São Paulo. Fundada em 1968, a UFSCar se destaca por seus cursos de engenharia e ciência, e pela pesquisa em diversas áreas do conhecimento.",
        link: "https://www.ufscar.br",
        cidade: "São Carlos",
    },
    {
        nome: "Universidade Federal de São João del-Rei (UFSJ)",
        descricao: "A Universidade Federal de São João del-Rei (UFSJ) é uma universidade pública federal brasileira, localizada em São João del-Rei, Minas Gerais. Fundada em 2002, a UFSJ oferece cursos em várias áreas e é reconhecida pela qualidade de seu ensino e pesquisa.",
        link: "https://www.ufsj.edu.br",
        cidade: "São João del-Rei",
    },
   

 {
        nome: "Universidade Federal de São Paulo (UNIFESP)",
        descricao: "A Universidade Federal de São Paulo (UNIFESP) é uma universidade pública federal brasileira, com campus em São Paulo e outras cidades. Fundada em 1933, a UNIFESP é destacada por sua excelência em saúde, ciências e humanidades.",
        link: "https://www.unifesp.br",
        cidade: "São Paulo",
    },
    {
        nome: "Universidade Federal de Uberlândia (UFU)",
        descricao: "A Universidade Federal de Uberlândia (UFU) é uma universidade pública federal brasileira, situada em Uberlândia, Minas Gerais. Fundada em 1969, a UFU oferece uma ampla gama de cursos e é conhecida por suas atividades de pesquisa e extensão.",
        link: "https://www.ufu.br",
        cidade: "Uberlândia",
    },
    {
        nome: "Universidade Federal de Viçosa (UFV)",
        descricao: "A Universidade Federal de Viçosa (UFV) é uma universidade pública federal brasileira, localizada em Viçosa, Minas Gerais. Fundada em 1969, a UFV é conhecida pela excelência em áreas como ciências agrárias, exatas e sociais.",
        link: "https://www.ufv.br",
        cidade: "Viçosa",
    },
    {
        nome: "Universidade Federal do ABC (UFABC)",
        descricao: "A Universidade Federal do ABC (UFABC) é uma universidade pública federal brasileira, localizada em Santo André, São Paulo. Fundada em 2005, a UFABC é destacada por sua abordagem inovadora ao ensino e pesquisa, especialmente em ciências e engenharia.",
        link: "https://www.ufabc.edu.br",
        cidade: "Santo André",
    },
    {
        nome: "Universidade Federal do Espírito Santo (UFES)",
        descricao: "A Universidade Federal do Espírito Santo (UFES) é uma universidade pública federal brasileira, situada em Vitória, Espírito Santo. Fundada em 1954, a UFES oferece uma ampla gama de cursos e é reconhecida por suas atividades de pesquisa e extensão.",
        link: "https://www.ufes.br",
        cidade: "Vitória",
    },
    {
        nome: "Universidade Federal do Estado do Rio de Janeiro (UNIRIO)",
        descricao: "A Universidade Federal do Estado do Rio de Janeiro (UNIRIO) é uma universidade pública federal brasileira, com sede no Rio de Janeiro. Fundada em 1979, a UNIRIO oferece uma variedade de cursos e é conhecida por sua contribuição à cultura e pesquisa.",
        link: "https://www.unirio.br",
        cidade: "Rio de Janeiro",
    },
    {
        nome: "Universidade Federal do Rio de Janeiro (UFRJ)",
        descricao: "A Universidade Federal do Rio de Janeiro (UFRJ) é uma das mais antigas e prestigiadas universidades do Brasil. Fundada em 1920, a UFRJ é conhecida por sua excelência acadêmica, com campus principal localizado no Rio de Janeiro.",
        link: "https://www.ufrj.br",
        cidade: "Rio de Janeiro",
    },
    {
        nome: "Universidade Federal do Triângulo Mineiro (UFTM)",
        descricao: "A Universidade Federal do Triângulo Mineiro (UFTM) é uma universidade pública federal brasileira, com sede em Uberaba, Minas Gerais. Fundada em 2002, a UFTM oferece uma ampla gama de cursos e é destacada por suas atividades de pesquisa e extensão.",
        link: "https://www.uftm.edu.br",
        cidade: "Uberaba",
    },
    {
        nome: "Universidade Federal dos Vales do Jequitinhonha e Mucuri (UFVJM)",
        descricao: "A Universidade Federal dos Vales do Jequitinhonha e Mucuri (UFVJM) é uma universidade pública federal brasileira, localizada em Diamantina, Minas Gerais. Fundada em 2005, a UFVJM se dedica ao ensino e à pesquisa na região dos Vales do Jequitinhonha e Mucuri.",
        link: "https://www.ufvjm.edu.br",
        cidade: "Diamantina",
    },
    {
        nome: "Universidade Federal Fluminense (UFF)",
        descricao: "A Universidade Federal Fluminense (UFF) é uma universidade pública federal brasileira, com sede em Niterói, Rio de Janeiro. Fundada em 1960, a UFF é conhecida por seu compromisso com a qualidade acadêmica e a pesquisa em diversas áreas.",
        link: "https://www.uff.br",
        cidade: "Niterói",
    },
    {
        nome: "Universidade Federal Rural do Rio de Janeiro (UFRRJ)",
        descricao: "A Universidade Federal Rural do Rio de Janeiro (UFRRJ) é uma universidade pública federal brasileira, localizada em Seropédica, Rio de Janeiro. Fundada em 1910, a UFRRJ se destaca por suas atividades acadêmicas e de pesquisa nas áreas rurais e agrárias.",
        link: "https://www.ufrrj.br",
        cidade: "Seropédica",
    },
    {
        nome: "Universidade Tecnológica Federal do Paraná (UTFPR)",
        descricao: "A Universidade Tecnológica Federal do Paraná (UTFPR) é uma universidade pública federal brasileira, com campus em diversas cidades do Paraná. Fundada em 2005, a UTFPR é conhecida por sua excelência em engenharia e tecnologia.",
        link: "https://www.utfpr.edu.br",
        cidade: "Curitiba",
    },
    {
        nome: "Universidade Federal da Fronteira Sul (UFFS)",
        descricao: "A Universidade Federal da Fronteira Sul (UFFS) é uma universidade pública federal brasileira, com campus em diversos estados do Sul do Brasil. Fundada em 2009, a UFFS é conhecida por seu foco no desenvolvimento regional e ensino superior de qualidade.",
        link: "https://www.uffs.edu.br",
        cidade: "Chapecó",
    },
    {
        nome: "Universidade Federal da Integração Latino-Americana (UNILA)",
        descricao: "A Universidade Federal da Integração Latino-Americana (UNILA) é uma universidade pública federal brasileira, localizada em Foz do Iguaçu, Paraná. Fundada em 2010, a UNILA é dedicada à integração e cooperação latino-americana por meio da educação superior.",
        link: "https://www.unila.edu.br",
        cidade: "Foz do Iguaçu",
    },
    {
        nome: "Universidade Federal de Ciências da Saúde de Porto Alegre (UFCSPA)",
        descricao: "A Universidade Federal de Ciências da Saúde de Porto Alegre (UFCSPA) é uma universidade pública federal brasileira, com sede em Porto Alegre, Rio Grande do Sul. Fundada em 1964, a UFCSPA é especializada em ciências da saúde e pesquisa biomédica.",
        link: "https://www.ufcspa.edu.br",
        cidade: "Porto Alegre",
    },
    {
        nome: "Universidade Federal de Pelotas (UFPel)",
        descricao: "A Universidade Federal de Pelotas (UFPel) é uma universidade pública federal brasileira, localizada em Pelotas, Rio Grande do Sul. Fundada em 1969, a UFPel oferece uma ampla gama de cursos e se destaca pela qualidade acadêmica e pesquisa.",
        link: "https://www.ufpel.edu.br",
        cidade: "Pelotas",
    },
    {
        nome: "Universidade Federal de Santa Catarina (UFSC)",
        descricao: "A Universidade Federal de Santa Catarina (UFSC) é uma universidade pública federal brasileira, com sede em Florianópolis, Santa Catarina. Fundada em 1960, a UFSC é conhecida por sua excelência acadêmica e contribuição para a pesquisa e a extensão.",
        link: "https://www.ufsc.br",
        cidade: "Florianópolis",
    },
    {
        nome: "Universidade Federal de Santa Maria (UFSM)",
        descricao: "A Universidade Federal de Santa Maria (UFSM) é uma universidade pública federal brasileira, situada em Santa Maria, Rio Grande do Sul. Fundada em 1960, a UFSM é reconhecida por seu ensino de qualidade e atividades de pesquisa.",
        link: "https://www.ufsm.br",
        cidade: "Santa Maria",
    },
    {
        nome: "Universidade Federal do Pampa (UNIPAMPA)",
        descricao: "A Universidade Federal do Pampa (UNIPAMPA) é uma universidade pública federal brasileira, localizada em São Gabriel, Rio Grande do Sul. Fundada em 2006, a UNIPAMPA é dedicada ao desenvolvimento regional e à oferta de educação superior de qualidade.",
        link: "https://www.unipampa.edu.br",
        cidade: "São Gabriel",
    },
    {
        nome: "Universidade Federal do Paraná (UFPR)",
        descricao: "A Universidade Federal do Paraná (UFPR) é uma universidade pública federal brasileira, situada em Curitiba, Paraná. Fundada em 1912, a UFPR é uma das mais tradicionais instituições de ensino superior do Brasil, conhecida por sua excelência acadêmica.",
        link: "https://www.ufpr.br",
        cidade: "Curitiba",
    },
    {
        nome: "Universidade Federal do Rio Grande (FURG)",
        descricao: "A Universidade Federal do Rio Grande (FURG) é uma universidade pública federal brasileira, localizada em Rio Grande, Rio Grande do Sul. Fundada em 1969, a FURG se destaca por sua contribuição ao ensino e pesquisa, especialmente em ciências do mar.",
        link: "https://www.furg.br",
        cidade: "Rio Grande",
    },
    {
        nome: "Universidade Federal de São Paulo (UNIFESP)",
        descricao: "A Universidade Federal de São Paulo (UNIFESP) é uma universidade pública federal brasileira, com campus em São Paulo e outras cidades. Fundada em 1933, a UNIFESP é destacada por sua excelência em saúde, ciências e humanidades.",
        link: "https://www.unifesp.br",
        cidade: "São Paulo",
    },
    {
        nome: "Universidade Federal da Bahia (UFBA)",
        descricao: "A Universidade Federal da Bahia (UFBA) é uma universidade pública federal brasileira, localizada em Salvador, Bahia. Fundada em 1946, a UFBA é reconhecida por sua excelência acadêmica e contribuição para a pesquisa e cultura na região nordeste do Brasil.",
        link: "https://www.ufba.br",
        cidade: "Salvador",
    },
    {
        nome: "Universidade Federal de Catalão (UFCat)",
        descricao: "A Universidade Federal de Catalão (UFCat) é uma universidade pública federal brasileira localizada em Catalão, Goiás. Fundada em 2002, a UFCat oferece uma variedade de cursos de graduação e pós-graduação, com foco na formação de profissionais qualificados e na pesquisa científica.",
        link: "https://www.ufcat.edu.br/",
        cidade: "Catalão"
    },
    {
        nome: "Universidade Federal do Sul da Bahia (UFSB)",
        descricao: "A Universidade Federal do Sul da Bahia (UFSB) é uma universidade pública federal brasileira situada em Porto Seguro, Bahia. Fundada em 2013, a UFSB tem o objetivo de promover a educação superior e a pesquisa na região sul da Bahia.",
        link: "https://www.ufsb.edu.br/",
        cidade: "Porto Seguro"
    },
    {
        nome: "Universidade Federal da Lusofonia Afro-Brasileira (UFLAB)",
        descricao: "A Universidade Federal da Lusofonia Afro-Brasileira (UFLAB) é uma universidade pública federal brasileira localizada em São Luís, Maranhão. Criada para fortalecer a integração cultural e acadêmica entre países lusófonos e o Brasil, a UFLAB promove a pesquisa e o ensino em áreas relacionadas à cultura e à língua portuguesa.",
        link: "https://www.uflab.edu.br/",
        cidade: "São Luís"
    },
    {
        nome: "Universidade Federal do Vale do São Francisco (Univasf)",
        descricao: "A Universidade Federal do Vale do São Francisco (Univasf) é uma universidade pública federal brasileira com sede em Petrolina, Pernambuco. Fundada em 2002, a Univasf oferece cursos de graduação e pós-graduação com ênfase no desenvolvimento regional e na pesquisa científica.",
        link: "https://www.univasf.edu.br/",
        cidade: "Petrolina"
    },
    {
        nome: "Universidade Federal Rural de Pernambuco (UFRPE)",
        descricao: "A Universidade Federal Rural de Pernambuco (UFRPE) é uma universidade pública federal brasileira localizada em Recife, Pernambuco. Fundada em 1912, a UFRPE é conhecida por suas atividades de ensino, pesquisa e extensão nas áreas de ciências agrárias, ciências sociais e ciências humanas.",
        link: "https://www.ufrpe.br/",
        cidade: "Recife"
    },
    {
        nome: "Universidade Federal Rural do Semi-Árido (UFERSA)",
        descricao: "A Universidade Federal Rural do Semi-Árido (UFERSA) é uma universidade pública federal brasileira localizada em Mossoró, Rio Grande do Norte. Criada em 2005, a UFERSA tem o foco na formação acadêmica e pesquisa, especialmente nas áreas relacionadas ao semiárido.",
        link: "https://www.ufersa.edu.br/",
        cidade: "Mossoró"
    },
    {
        nome: "Universidade Federal do Agreste de Pernambuco (UFAPE)",
        descricao: "A Universidade Federal do Agreste de Pernambuco (UFAPE) é uma universidade pública federal brasileira situada em Caruaru, Pernambuco. Fundada em 2013, a UFAPE visa atender as demandas educacionais e de pesquisa da região agreste do estado.",
        link: "https://www.ufape.edu.br/",
        cidade: "Caruaru"
    },
    {
        nome: "Universidade Federal do Delta do Parnaíba (UFDPar)",
        descricao: "A Universidade Federal do Delta do Parnaíba (UFDPar) é uma universidade pública federal brasileira localizada em Parnaíba, Piauí. Estabelecida em 2013, a UFDPar oferece uma variedade de cursos de graduação e pós-graduação, com ênfase no desenvolvimento regional e nas necessidades locais.",
        link: "https://www.ufdpar.edu.br/",
        cidade: "Parnaíba"
    },
    {
        nome: "Universidade Federal do Norte do Tocantins (UFNT)",
        descricao: "A Universidade Federal do Norte do Tocantins (UFNT) é uma universidade pública federal brasileira com sede em Araguaína, Tocantins. Fundada em 2008, a UFNT oferece cursos de graduação e pós-graduação com foco no desenvolvimento regional e na pesquisa científica.",
        link: "https://www.ufnt.edu.br/",
        cidade: "Araguaína"
    }
];